export const webData = [
  {
    section: "Web Applications",
    desc: "Fully dynamic web pages for various interactive functions. Made with technologies, features and libraries like Vite React, various APIs, localStorage, Day.js, and shadcn/ui.",
  },
  {
    name: "Game App",
    desc: "App that allows for keeping a video game backlog and completion list. Also allows for searching and displaying info on games. Made with RAWG.io API - API for game info. Made with React, Tailwind CSS, Vite, shadcn/ui, TypeScript",
    mobileimage: "./web/game app mobile.png",
    desktopimage: "./web/game app desktop.png",
    liveurl: "https://jayaey.github.io/game-app/",
    github: "https://github.com/jayAEY/game-app",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Vite",
      "API",
      "Tailwind CSS",
      "TypeScript",
    ],
  },
  {
    name: "Spending App",
    desc: "Responsive web page that displays an expense chart with dynamically sized bars. Allows for inputting and saving spending and balance data. Made entirely with vanilla HTML, CSS and JavaScript",
    mobileimage: "./web/expense chart mobile.png",
    desktopimage: "./web/expense chart desktop.png",
    liveurl: "https://jayaey.github.io/expense-chart-component/",
    github: "https://github.com/jayAEY/expense-chart-component",
    technologies: ["HTML", "CSS", "JavaScript"],
  },
  {
    name: "Age Calculator",
    desc: "Age calculator made with Vite, React and Tailwind CSS",
    mobileimage: "./web/age calculator mobile.png",
    desktopimage: "./web/age calculator desktop.png",
    liveurl: "https://jayaey.github.io/age-calculator/",
    github: "https://github.com/jayAEY/age-calculator",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Vite",
      "Tailwind CSS",
    ],
  },
  {
    name: "Github User Display",
    desc: "App that displays github user info. Allows for searching. Made with vanilla HTML, CSS, JavaScript and the Github REST API",
    mobileimage: "./web/github user display mobile.png",
    desktopimage: "./web/github user display desktop.png",
    liveurl: "https://jayaey.github.io/github-user-display/",
    github: "https://github.com/jayAEY/github-user-display",
    technologies: ["HTML", "CSS", "JavaScript", "API"],
  },
  {
    name: "Time Display",
    desc: "App that displays time based on a certain Canadian timezone. The timezone can be changed. Made with HTML, CSS, Bootstrap, JavaScript, Micromodal.js and Day.js",
    mobileimage: "./web/time display mobile.png",
    desktopimage: "./web/time display desktop.png",
    liveurl: "https://jayaey.github.io/time-display/",
    github: "https://github.com/jayAEY/time-display",
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap"],
  },
  {
    name: "Quote Generator",
    desc: "Advice generator app that retrieves random advice from an API. Made entirely with vanilla HTML, CSS and JavaScript",
    mobileimage: "./web/quote generator mobile.png",
    desktopimage: "./web/quote generator desktop.png",
    liveurl: "https://jayaey.github.io/advice-generator/",
    github: "https://github.com/jayAEY/advice-generator",
    technologies: ["HTML", "CSS", "JavaScript", "API"],
  },
  {
    section: "Misc Components",
    desc: "These projects focused on specific features that could be used in bigger projects. Features included a filtered display, a unique navbar hover menu, and a countdown animated display with a fireworks animation.",
  },

  {
    name: "Countdown Clock",
    desc: "Responsive web page with animated countdown timer. Made with mostly vanilla HTML, CSS and JavaScript. GSAP and canvas-confetti were used for the animations.",
    mobileimage: "./web/countdown clock mobile.png",
    desktopimage: "./web/countdown clock desktop.png",
    liveurl: "https://jayaey.github.io/launch-countdown-timer/",
    github: "https://github.com/jayAEY/launch-countdown-timer",
    technologies: ["HTML", "CSS", "JavaScript", "API", "GSAP"],
  },
  {
    name: "Hover Menu",
    desc: "Landing Page with a menu that shows when you hover over a nav link. Made with vanilla HTML, CSS and JavaScript",
    mobileimage: "./web/hover menu mobile.png",
    desktopimage: "./web/hover menu desktop.png",
    liveurl: "https://jayaey.github.io/ondeck-landing-page/",
    github: "https://github.com/jayAEY/ondeck-landing-page",
    technologies: ["HTML", "CSS", "JavaScript"],
  },
  {
    name: "Rating Component",
    desc: "Responsive web page for a rating component. Allows for giving ratings and displaying an average rating based on localStorage data. Made entirely with vanilla HTML, CSS and JavaScript",
    mobileimage: "./web/rating component mobile.png",
    desktopimage: "./web/rating component desktop.png",
    liveurl: "https://jayaey.github.io/interactive-rating-component/",
    github: "https://github.com/jayAEY/interactive-rating-component",
    technologies: ["HTML", "CSS", "JavaScript"],
  },
  {
    name: "Job Filtering Component",
    desc: "Responsive web page that displays job listings with a filters them according to selected keywords. Made entirely with vanilla HTML, CSS and JavaScript.",
    mobileimage: "./web/job filtering mobile.png",
    desktopimage: "./web/job filtering desktop.png",
    liveurl: "https://jayaey.github.io/job-listings-with-filtering/",
    github: "https://github.com/jayAEY/job-listings-with-filtering",
    technologies: ["HTML", "CSS", "JavaScript"],
  },

  {
    name: "Social Links Display",
    desc: "Social media reference landing page made with vanilla HTML, CSS",
    mobileimage: "./web/social links display mobile.png",
    desktopimage: "./web/social links display desktop.png",
    liveurl: "https://jayaey.github.io/social-links-profile/",
    github: "https://github.com/jayAEY/social-links-profile",
    technologies: ["HTML", "CSS"],
  },
  {
    section: "Layouts",
    desc: "Webpages that display various layouts, either for the full pages, or specific parts of them. These projects were typically designed focused and were meant to display various design possibilities ",
  },
  {
    name: "Room Landing Page",
    desc: "Responive landing page with a precise layout. Includes a mobile menu and image slideshow made from scratch. Made entirely with vanilla HTML, CSS and JavaScript",
    mobileimage: "./web/room landing page mobile.png",
    desktopimage: "./web/room landing page desktop.png",
    liveurl: "https://jayaey.github.io/room-homepage/",
    github: "https://github.com/jayAEY/room-homepage",
    technologies: ["HTML", "CSS", "JavaScript"],
  },

  {
    name: "Stats Preview Component",
    desc: "Stat display made with Vite, React and Tailwind",
    mobileimage: "./web/stats preview component mobile.png",
    desktopimage: "./web/stats preview component desktop.png",
    liveurl: "https://jayaey.github.io/stats-preview-card-component-main/",
    github: "https://github.com/jayAEY/stats-preview-card-component-main",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Vite",
      "Tailwind CSS",
    ],
  },
  {
    name: "Blog Preview Card",
    desc: "Preview component for a blog. Made with  vanilla HTML, CSS",
    mobileimage: "./web/blog preview card mobile.png",
    desktopimage: "./web/blog preview card desktop.png",
    liveurl: "https://jayaey.github.io/blog-preview-card/",
    github: "https://github.com/jayAEY/blog-preview-card",
    technologies: ["HTML", "CSS"],
  },
  {
    name: "Newsletter Subscription",
    desc: "Popup for and email subscription. Made with vanilla HTML, CSS and JavaScript",
    mobileimage: "./web/newsletter popup mobile.png",
    desktopimage: "./web/newsletter popup desktop.png",
    liveurl: "https://github.com/jayAEY/newsletter-popup",
    github: "https://github.com/jayAEY/newsletter-popup",
    technologies: ["HTML", "CSS"],
  },
  {
    name: "Snipper Landing Page",
    desc: "Responsive landing Page made vanilla HTML, CSS and JavaScript",
    mobileimage: "./web/snipper landing page mobile.png",
    desktopimage: "./web/snipper landing page desktop.png",
    liveurl: "https://jayaey.github.io/snipper-landing-page/",
    github: "https://github.com/jayAEY/snipper-landing-page",
    technologies: ["HTML", "CSS", "JavaScript"],
  },
  {
    name: "Sign Up Page",
    desc: "Popup form for login/registration. Made with vanilla HTML and CSS",
    mobileimage: "./web/sign up page mobile.png",
    desktopimage: "./web/sign up page desktop.png",
    liveurl: "https://jayaey.github.io/sign-in-pop-up/",
    github: "https://github.com/jayAEY/sign-in-pop-up",
    technologies: ["HTML", "CSS"],
  },
  {
    name: "Comment Section",
    desc: "Social media reference landing page made with vanilla HTML, and CSS",
    mobileimage: "./web/comment section mobile.png",
    desktopimage: "./web/comment section desktop.png",
    liveurl: "https://jayaey.github.io/comment-module/",
    github: "https://github.com/jayAEY/comment-module",
    technologies: ["HTML", "CSS"],
  },
];
